### ISSUE TITLE
how do i fuzz filesystem

### ISSUE THREAD

**Issue by ProbablyFaiz** [n-wach/fuzzing-with-cmake#1]
thank

**Comment by n-wach** [comment]
Hi Faiz. Thanks for the excellent question!

Unfortunately, I'm not aware of an easy way to fuzz a filesystem in general. Luckily, I do have a repo with some boilerplate code for fuzzing a libFUSE-based filesystem. It might help you get started.

You can check that out here: https://github.com/n-wach/fuse-fuzzer
